# Generated by Django 5.1.1 on 2024-09-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Producto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='servicio',
            new_name='producto',
        ),
    ]
